#!/usr/bin/env ruby
require 'net/http'
require 'json'
require 'uri'
require 'dotenv'
Dotenv.load

outputfile="#{Dir.pwd}/.git/hooks/outputfile.json"
if File.exist?(outputfile)
	puts "Sending commits to spritle dashboard ......."
	origin_url = `git config --get remote.origin.url`
	unless (origin_url.include?('https://') || origin_url.include?('http://'))
		origin_url = origin_url.gsub("git@", "http://").gsub(".git","").gsub(".com:", ".com/")
	else
		origin_url = origin_url.gsub(".git","")
	end
	log_time_values = {"commits" => [], "origin_url" => origin_url }
	log_time_values["commits"] = File.read(outputfile)
	url = ENV["GIT_LOG_TIME_CALLBACK_URL"]
	uri = URI.parse(url)
	data = {"name" => "tbone"}
	headers = {"Content-Type" => "application/json"}
	http = Net::HTTP.new(uri.host,uri.port)
	response = http.post(uri.path,log_time_values.to_json,headers)
	if response.body["success"]
	  File.delete(outputfile)
	end
end